/**
 * Reads the API version the INSTALLED stripe-node package pins by DEFAULT —
 * the pin a repo has without a single `apiVersion` anywhere in its source
 * (US-9).
 *
 * ## Why this exists
 * US-7 closed the readable pin (`new Stripe(key, { apiVersion: '2023-08-16' })`).
 * The residual hole is the pin nobody wrote: since stripe-node v12.0.0 the SDK
 * sends a `Stripe-Version` header even when the caller passes no `apiVersion`,
 * because its core does
 *
 *     version: props.apiVersion || DEFAULT_API_VERSION
 *
 * and, from v12 on, `DEFAULT_API_VERSION = apiVersion.ApiVersion` — the literal
 * of the generated `apiVersion.js` shipped in the tarball. So a repo on
 * stripe v13 with no `apiVersion` in its code really runs on `2023-08-16`.
 * US-7 classifies it `no-option`, applies a `2025-03-31.basil` change and ships
 * a green-but-wrong PR: the agnai scenario (US-6) minus its explicit pin.
 *
 * ## Two files, ZERO lookup table (decision D1, US-9)
 * They answer two different questions and both are needed:
 *   - `package.json` -> `version` -> major: "does this SDK pin at all?" A
 *     BOOLEAN threshold, `major >= 12`, and nothing else. It is NEVER used to
 *     infer a date.
 *   - `{cjs,esm,lib}/apiVersion.js`: "pinned to WHICH version?" The exact
 *     literal, READ, never derived.
 *
 * A hardcoded SDK -> API-version table was rejected on purpose: its failure
 * mode is precisely the one this module exists to close. Every new stripe-node
 * major would fall off the end of the table and silently become a false
 * negative again. The file, by contrast, is regenerated by Stripe at every
 * release and shipped in the tarball — it cannot go stale.
 *
 * ## Field notes (18 npm tarballs inspected, 8.222.0 -> 22.6.1, 2026-09-05)
 *   - There is NO `API_VERSION` file, in any version, nor in the git repo.
 *     `OPENAPI_VERSION` (v18+, `'v2442'`) is a spec build number, not a date.
 *   - The path moved: `lib/apiVersion.js` up to 11.17, `cjs/` + `esm/` from
 *     11.18 on. The boundary does NOT follow the major (11.0.0 = `lib/`,
 *     11.18.0 = `cjs/`), so the candidates are PROBED, never deduced.
 *   - The threshold is exactly v12: `lib/apiVersion.js` exists as far back as
 *     v9, but the core declares `DEFAULT_API_VERSION = null` through 11.18.0 —
 *     no header at all, the account's own default applies. 11.18.0 and 12.0.0
 *     shipped the same day, 22 minutes apart, and behave differently: the
 *     threshold is the major, not the date.
 *
 * ## Scope
 * `stripe` only — this is a Stripe mechanism, and guessing that another
 * vendor's SDK behaves the same way would be exactly the kind of invention
 * this module refuses. Any other module resolves to "we could not look".
 *
 * 100% ts-morph, on a THROWAWAY in-memory project. The target's own `Project`
 * excludes `node_modules` (US-1) and must keep excluding it: this file is
 * vendor code, never a candidate for editing.
 */
import fs from 'node:fs';
import path from 'node:path';
import { Node, Project, SyntaxKind } from 'ts-morph';
// Same readability rule on both sides of the guard: a value this module accepts
// must be a value `isPinnedBefore` can compare. Duplicating the rule here would
// let the two drift apart in exactly the code whose job is to prevent silent
// wrongness.
import { apiVersionDate } from '../changes/api-version.js';

/** The only vendor whose implicit pin is a documented, verified mechanism. */
const SUPPORTED_VENDOR = 'stripe';

/**
 * First stripe-node major whose core does `props.apiVersion || ApiVersion`
 * instead of `props.apiVersion || null`. Verified on 11.18.0 vs 12.0.0.
 */
const FIRST_IMPLICIT_PIN_MAJOR = 12;

/**
 * Where the generated file has lived, newest layout first. Probed in order,
 * because the layout change (11.18.0) does not line up with any major.
 */
const API_VERSION_FILE_CANDIDATES = ['cjs', 'esm', 'lib'] as const;

/** The name of the export that carries the API version — and NOT its neighbour. */
const API_VERSION_EXPORT = 'ApiVersion';

/**
 * What the installed package told us.
 *
 * The three `unresolved` reasons are kept apart on purpose (decision D3): they
 * call for three different sentences to a human, and merging them would let
 * "we could not look" be shown as "there is no pin".
 */
export type InstalledSdkApiVersion =
  | {
      status: 'resolved';
      /** The literal read from `apiVersion.js`, verbatim (`'2023-08-16'`). */
      apiVersion: string;
      /** The installed package version (`'13.0.0'`) — for disclosure only. */
      sdkVersion: string;
      /** Absolute path of the `apiVersion.js` we read. */
      filePath: string;
      line: number;
    }
  | {
      status: 'unresolved';
      reason:
        /** No `node_modules/<vendor>` at all: a clone nobody installed. We did not look. */
        | 'sdk-not-installed'
        /** Major <= 11: the SDK sends no header, so the ACCOUNT default applies — not knowable statically. */
        | 'sdk-predates-implicit-pin'
        /** Package there but `package.json` / `apiVersion.js` missing, corrupt or in an unseen shape. */
        | 'sdk-version-unreadable';
      /** Present when we got far enough to read it. Disclosure only. */
      sdkVersion?: string;
    };

/** Peels `(x)`, `x as T`, `x satisfies T` — same rule as the client-option reader. */
function unwrap(node: Node): Node {
  let current = node;
  for (;;) {
    if (
      Node.isAsExpression(current)
      || Node.isSatisfiesExpression(current)
      || Node.isParenthesizedExpression(current)
    ) {
      current = current.getExpression();
      continue;
    }
    return current;
  }
}

/**
 * The string literal an `ApiVersion` export is assigned, or `null`.
 *
 * Three shapes, all three observed across the 18 tarballs:
 *   `exports.ApiVersion = '<v>'`        BinaryExpression (CJS build output)
 *   `export const ApiVersion = '<v>'`   VariableDeclaration (ESM build output)
 *   `module.exports = {ApiVersion: '<v>'}`  PropertyAssignment (older shape)
 *
 * Three traps, each verified against a real tarball and each the reason for one
 * condition below:
 *   - the right-hand side MUST be a `StringLiteral`. tsc emits
 *     `exports.ApiMajorVersion = exports.ApiVersion = void 0;` before the real
 *     assignment (v22); accepting any right-hand side would read `void 0`.
 *   - never "the first literal in the file": that is `'use strict'` on every
 *     v12+ build.
 *   - never `ApiMajorVersion`: it holds a CHANNEL NAME (`'clover'`,
 *     `'dahlia'`), not a date. The name is matched exactly.
 * A value that is not a readable API version is refused too — a shape we do not
 * understand must read as "unreadable", never as a pin.
 */
function readApiVersionLiteral(content: string): { version: string; line: number } | null {
  // A throwaway, in-memory project: the vendor file must never enter the
  // target's Project, and must never touch its file system either.
  const project = new Project({ useInMemoryFileSystem: true });
  const sourceFile = project.createSourceFile('apiVersion.js', content, { overwrite: true });

  let found: { version: string; line: number } | null = null;

  sourceFile.forEachDescendant((node, traversal) => {
    let value: Node | undefined;

    if (Node.isBinaryExpression(node)) {
      if (node.getOperatorToken().getKind() !== SyntaxKind.EqualsToken) return;
      const left = unwrap(node.getLeft());
      if (!Node.isPropertyAccessExpression(left) || left.getName() !== API_VERSION_EXPORT) return;
      value = unwrap(node.getRight());
    } else if (Node.isVariableDeclaration(node)) {
      if (node.getName() !== API_VERSION_EXPORT) return;
      const initializer = node.getInitializer();
      if (!initializer) return;
      value = unwrap(initializer);
    } else if (Node.isPropertyAssignment(node)) {
      if (node.getName() !== API_VERSION_EXPORT) return;
      const initializer = node.getInitializer();
      if (!initializer) return;
      value = unwrap(initializer);
    } else {
      return;
    }

    // `void 0`, an identifier, a call — anything that is not a literal string
    // is not an answer.
    if (!Node.isStringLiteral(value) && !Node.isNoSubstitutionTemplateLiteral(value)) return;

    const version = value.getLiteralValue();
    if (apiVersionDate(version) === null) return;

    found = { version, line: value.getSourceFile().getLineAndColumnAtPos(value.getStart()).line };
    traversal.stop();
  });

  return found;
}

/** The `version` field of an installed package's manifest, or `null` if unreadable. */
function readInstalledVersion(packageDir: string): string | null {
  try {
    const manifest: unknown = JSON.parse(fs.readFileSync(path.join(packageDir, 'package.json'), 'utf8'));
    const version = (manifest as { version?: unknown }).version;
    return typeof version === 'string' && version.length > 0 ? version : null;
  } catch {
    return null; // absent, unreadable or not JSON — all "we cannot tell".
  }
}

/** The leading integer of a semver string, or `null`. Never a guess. */
function majorOf(version: string): number | null {
  const head = version.split('.')[0];
  return /^\d+$/.test(head) ? Number(head) : null;
}

/**
 * Resolves the API version the vendor SDK installed under `projectPath` pins by
 * default.
 *
 * `projectPath` is the WORKSPACE root, not the user's checkout: the pipeline
 * symlinks the target's `node_modules` into the workspace before the guard runs
 * (`linkNodeModules`, US-7), so the path we report relativizes cleanly to
 * `node_modules/stripe/cjs/apiVersion.js`. The symlink is deliberately NOT
 * resolved — realpath'ing it would leak the user's absolute checkout path into
 * the PR body.
 *
 * Every failure is an explicit `unresolved` reason. There is no "assume latest"
 * branch anywhere in this file, by design.
 */
export function resolveInstalledSdkDefaultApiVersion(
  projectPath: string,
  vendorModule: string,
): InstalledSdkApiVersion {
  // Not Stripe: we have no verified mechanism, so we say we could not look
  // rather than inventing one. This is the multi-vendor scope guard, in code.
  if (vendorModule !== SUPPORTED_VENDOR) return { status: 'unresolved', reason: 'sdk-version-unreadable' };

  const packageDir = path.join(projectPath, 'node_modules', vendorModule);
  if (!fs.existsSync(packageDir)) return { status: 'unresolved', reason: 'sdk-not-installed' };

  const sdkVersion = readInstalledVersion(packageDir);
  if (sdkVersion === null) return { status: 'unresolved', reason: 'sdk-version-unreadable' };

  const major = majorOf(sdkVersion);
  if (major === null) return { status: 'unresolved', reason: 'sdk-version-unreadable', sdkVersion };

  // The boolean threshold, and the ONLY thing the major is ever used for.
  if (major < FIRST_IMPLICIT_PIN_MAJOR) {
    return { status: 'unresolved', reason: 'sdk-predates-implicit-pin', sdkVersion };
  }

  for (const dir of API_VERSION_FILE_CANDIDATES) {
    const filePath = path.join(packageDir, dir, 'apiVersion.js');
    let content: string;
    try {
      content = fs.readFileSync(filePath, 'utf8');
    } catch {
      continue; // Not this layout — try the next candidate.
    }

    const literal = readApiVersionLiteral(content);
    if (literal === null) break; // The file is there but in a shape we do not understand.
    return { status: 'resolved', apiVersion: literal.version, sdkVersion, filePath, line: literal.line };
  }

  return { status: 'unresolved', reason: 'sdk-version-unreadable', sdkVersion };
}
